In [88]:
import cma
import numpy as np 
import matplotlib.pyplot as plt 
import pickle 

In [85]:
def f(x):
    return np.linalg.norm(x-np.array([0.9,0.2]))

In [86]:
es = cma.CMAEvolutionStrategy(2 * [0], 0.3, { 'bounds': [-np.ones(2), np.ones(2)*0.9]})
while not es.stop():
    solutions = es.ask()
    es.tell(solutions, [f(x) for x in solutions])
    es.logger.add()  # write data to disc to be plotted
    es.disp()
    print(es.result[6])

(3_w,6)-aCMA-ES (mu_w=2.0,w_1=63%) in dimension 2 (seed=498397, Tue Oct 29 16:13:02 2019)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      6 2.256035011400316e-01 1.0e+00 3.97e-01  4e-01  5e-01 0:00.0
[0.50761345 0.40127827]
    2     12 2.681640602247772e-01 1.5e+00 5.40e-01  5e-01  8e-01 0:00.0
[0.82702368 0.54730361]
    3     18 1.709234997472332e-01 2.1e+00 4.25e-01  4e-01  5e-01 0:00.0
[0.53497074 0.37424946]
[0.48915028 0.2953639 ]
[0.35643502 0.23138465]
[0.27337806 0.17490259]
[0.19747898 0.11218948]
[0.15445013 0.10221103]
[0.10856759 0.07404687]
[0.1000292  0.05841752]
[0.07590473 0.04192222]
[0.05498701 0.03083702]
[0.05221772 0.02539888]
[0.06539002 0.02286788]
[0.0451761  0.01629873]
[0.04042488 0.01290568]
[0.02594328 0.00757363]
[0.02974261 0.0061949 ]
[0.02984092 0.00612934]
[0.02046012 0.00364156]
[0.01381877 0.00293704]
[0.01239946 0.00263548]
[0.00966929 0.00199664]
[0.00865682 0.00207136]
[0.01044133 0.00217919]
[0.00994677 0.00176

In [84]:
np.zeros(1)

array([0.])

In [81]:
a[0]

array([0.9, 0.2])

In [65]:
es = cma.CMAEvolutionStrategy(2 * [0], 0.5)
es.logger.load(filenameprefix='outcmaes/')

(3_w,6)-aCMA-ES (mu_w=2.0,w_1=63%) in dimension 2 (seed=441489, Tue Oct 29 15:27:39 2019)


In [67]:
es.logger.xmean[-1]

array([1.29000000e+02, 7.74000000e+02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 9.94999894e-01, 2.00000000e-01])

In [103]:
with open("exp/data/data.pk", 'rb') as f:
    data = pickle.load(f)

In [104]:
data

([array([0.29440282, 0.87466748, 0.47739361, 0.04677332, 0.96314915,
         0.20880917, 0.17681849, 0.11482404, 0.79937044, 0.41276506,
         0.41241987, 0.01114245, 0.08683635, 0.97107915, 0.42539708,
         0.78290153])],
 [array(-1.77140805)],
 array([   0.5656664 ,  -85.73224189,   -0.58742914, -174.96453059,
          -1.        ]))